import { Store, Category, City } from './types';

export const AVAILABLE_CITIES: City[] = [
  { id: 'sp', name: 'São Paulo', state: 'SP' },
  { id: 'rj', name: 'Rio de Janeiro', state: 'RJ' },
  { id: 'bh', name: 'Belo Horizonte', state: 'MG' },
  { id: 'cur', name: 'Curitiba', state: 'PR' },
];

export const CATEGORIES: Category[] = [
  { id: 'all', name: 'Tudo', iconName: 'Utensils' },
  { id: 'burger', name: 'Lanches', iconName: 'Beef' },
  { id: 'pizza', name: 'Pizza', iconName: 'Pizza' },
  { id: 'japanese', name: 'Japonesa', iconName: 'Fish' },
  { id: 'brazilian', name: 'Brasileira', iconName: 'CookingPot' },
  { id: 'acai', name: 'Açaí', iconName: 'IceCream' },
  { id: 'drinks', name: 'Bebidas', iconName: 'Beer' },
];

export const STORES: Store[] = [
  {
    id: '1',
    name: 'Burger King do Bairro',
    category: 'burger',
    rating: 4.8,
    deliveryTime: '25-35 min',
    deliveryFee: 5.90,
    imageUrl: 'https://picsum.photos/800/400?random=1',
    logoUrl: 'https://picsum.photos/100/100?random=101',
    isOpen: true,
    city: 'São Paulo',
    storeUrl: '#',
  },
  {
    id: '2',
    name: 'Pizzaria Molho de Tomate',
    category: 'pizza',
    rating: 4.5,
    deliveryTime: '40-50 min',
    deliveryFee: 0,
    imageUrl: 'https://picsum.photos/800/400?random=2',
    logoUrl: 'https://picsum.photos/100/100?random=102',
    isOpen: true,
    city: 'São Paulo',
    storeUrl: '#',
  },
  {
    id: '3',
    name: 'Sushi House Premium',
    category: 'japanese',
    rating: 4.9,
    deliveryTime: '30-45 min',
    deliveryFee: 12.00,
    imageUrl: 'https://picsum.photos/800/400?random=3',
    logoUrl: 'https://picsum.photos/100/100?random=103',
    isOpen: true,
    city: 'Rio de Janeiro',
    storeUrl: '#',
  },
  {
    id: '4',
    name: 'Açaí da Esquina',
    category: 'acai',
    rating: 4.2,
    deliveryTime: '15-25 min',
    deliveryFee: 3.50,
    imageUrl: 'https://picsum.photos/800/400?random=4',
    logoUrl: 'https://picsum.photos/100/100?random=104',
    isOpen: true,
    city: 'Belo Horizonte',
    storeUrl: '#',
  },
  {
    id: '5',
    name: 'Restaurante Sabor Mineiro',
    category: 'brazilian',
    rating: 4.7,
    deliveryTime: '50-60 min',
    deliveryFee: 0,
    imageUrl: 'https://picsum.photos/800/400?random=5',
    logoUrl: 'https://picsum.photos/100/100?random=105',
    isOpen: false,
    city: 'Belo Horizonte',
    storeUrl: '#',
  },
  {
    id: '6',
    name: 'Adega 24h',
    category: 'drinks',
    rating: 4.0,
    deliveryTime: '20-30 min',
    deliveryFee: 7.00,
    imageUrl: 'https://picsum.photos/800/400?random=6',
    logoUrl: 'https://picsum.photos/100/100?random=106',
    isOpen: true,
    city: 'Curitiba',
    storeUrl: '#',
  },
  {
    id: '7',
    name: 'Mega Lanches Artesanais',
    category: 'burger',
    rating: 4.6,
    deliveryTime: '35-45 min',
    deliveryFee: 4.90,
    imageUrl: 'https://picsum.photos/800/400?random=7',
    logoUrl: 'https://picsum.photos/100/100?random=107',
    isOpen: true,
    city: 'São Paulo',
    storeUrl: '#',
  },
  {
    id: '8',
    name: 'Forneria Italiana',
    category: 'pizza',
    rating: 4.3,
    deliveryTime: '45-55 min',
    deliveryFee: 8.50,
    imageUrl: 'https://picsum.photos/800/400?random=8',
    logoUrl: 'https://picsum.photos/100/100?random=108',
    isOpen: true,
    city: 'Rio de Janeiro',
    storeUrl: '#',
  },
];